### ISSUE TITLE
닉네임 hovering시 가입일 나오도록!

### ISSUE THREAD

**Issue by ilbestudent** [ilbestudent/ilbe_shortcut#46]

**Comment by ilbestudent** [comment]
이건 절대로 하지 말도록

**Comment by soldierf7** [comment]
요새 쌓인 게 너무 많아서 홧김에 치다가 욕까지 해 버렸다 ㅡㅡ
잉팝에 +가입일 이유:
요새 뉴비 (메갈 웜드가 다수)는 너무 버릇이 없어서 customblocker 로 걸러놓고 봐야됨
특히 메갈년들 많이 들어오는 거 알지 customblocker 로 다 걸러야 됨 그년들은 계도가 안 됨
욕해서 진심으로 미안하다 이기 가뜩이나 날도 더운데 고생 많다 이기
한 줄 요약 다수의 메갈 웜드 사전 차단을 위해서라도 잉팝에 가입일뜨게 좀 해 달라
